import Navbar from "@/components/Navbar";
import SayLogLogo from "@/components/SayLogLogo";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#19181a] text-cream">
      <Navbar />

      <section className="pt-24 pb-10 sm:pt-32 sm:pb-14 md:pt-40 md:pb-20">
        <div className="mx-auto max-w-4xl px-5 sm:px-6 md:px-10">
          <p className="mb-3 text-xs font-medium uppercase tracking-widest text-accent sm:text-sm">Legal</p>
          <h1 className="text-3xl font-semibold tracking-[-0.02em] sm:text-4xl md:text-5xl">Terms and Conditions</h1>
          <p className="mt-4 text-sm text-muted sm:text-base">Last updated: March 9, 2026</p>
        </div>
      </section>

      <section className="pb-16 sm:pb-20 md:pb-24">
        <div className="mx-auto max-w-4xl px-5 sm:px-6 md:px-10">
          <TermsSection title="1. Acceptance of Terms">
            <TermsBody>
              By downloading, installing, or using SayLog ("the app"), you agree to be bound by these Terms
              and Conditions. If you do not agree, please do not use the app.
            </TermsBody>
          </TermsSection>

          <TermsSection title="2. About SayLog">
            <TermsBody>
              SayLog is a voice-first calorie and nutrition tracking application designed for Indian languages
              and English. The app allows you to log meals by speaking and uses AI services to estimate
              nutritional information.
            </TermsBody>
            <TermsBody>
              SayLog is operated by RWE Labs. Nutritional information provided by the app is estimated using
              AI and should not be treated as medical or dietary advice.
            </TermsBody>
          </TermsSection>

          <TermsSection title="3. User Accounts">
            <TermsBody>You must create an account to use SayLog. You are responsible for:</TermsBody>
            <TermsList
              items={[
                "Maintaining the confidentiality of your credentials",
                "All activity that occurs under your account",
                "Providing accurate information during account registration",
              ]}
            />
            <TermsBody>
              We reserve the right to suspend or terminate accounts that violate these Terms.
            </TermsBody>
          </TermsSection>

          <TermsSection title="4. Acceptable Use">
            <TermsBody>You agree not to:</TermsBody>
            <TermsList
              items={[
                "Use the app for any unlawful or fraudulent purpose",
                "Attempt to reverse-engineer, decompile, or tamper with the app",
                "Transmit harmful, offensive, or malicious content",
                "Use automated systems to access the app in a way that exceeds reasonable personal use",
              ]}
            />
          </TermsSection>

          <TermsSection title="5. Third-Party Services">
            <TermsBody>
              SayLog integrates with the following third-party services to deliver its features. By using the
              app, you acknowledge that your data may be processed by these providers:
            </TermsBody>

            <TermsSubheading>Sarvam AI (Speech-to-Text)</TermsSubheading>
            <TermsBody>
              Your voice recordings are sent to Sarvam AI for transcription into text. Audio data is
              processed in accordance with Sarvam AI&apos;s terms of service and is not stored by SayLog beyond
              the duration of each session.
            </TermsBody>

            <TermsSubheading>Google Gemini (Nutrition Estimation)</TermsSubheading>
            <TermsBody>
              Transcribed text describing your meals is sent to Google Gemini to estimate calorie and
              macronutrient content. This data is processed under Google&apos;s API terms of service.
            </TermsBody>

            <TermsSubheading>PostHog (Analytics)</TermsSubheading>
            <TermsBody>
              We use PostHog to collect anonymized usage analytics to help us improve the app. No personally
              identifiable information is intentionally sent to PostHog.
            </TermsBody>

            <TermsSubheading>Supabase (Data Storage)</TermsSubheading>
            <TermsBody>
              Your profile, food logs, and settings are stored securely on Supabase. All data is protected by
              row-level security and accessible only to you.
            </TermsBody>
          </TermsSection>

          <TermsSection title="6. Nutritional Disclaimer">
            <TermsBody>
              Calorie and macronutrient estimates provided by SayLog are generated by AI and are
              approximations only. They are not intended to replace professional medical, nutritional, or
              dietary advice. Always consult a qualified healthcare professional before making significant
              changes to your diet.
            </TermsBody>
          </TermsSection>

          <TermsSection title="7. Intellectual Property">
            <TermsBody>
              All content, trademarks, logos, and software in the app are the property of RWE Labs or its
              licensors. You may not reproduce, distribute, or create derivative works without our prior
              written consent.
            </TermsBody>
          </TermsSection>

          <TermsSection title="8. Disclaimer of Warranties">
            <TermsBody>
              The app is provided "as is" without warranties of any kind, express or implied. We do not
              guarantee that the app will be error-free, uninterrupted, or meet your specific requirements.
            </TermsBody>
          </TermsSection>

          <TermsSection title="9. Limitation of Liability">
            <TermsBody>
              To the maximum extent permitted by law, RWE Labs shall not be liable for any indirect,
              incidental, consequential, or punitive damages arising from your use of or inability to use the
              app, even if we have been advised of the possibility of such damages.
            </TermsBody>
          </TermsSection>

          <TermsSection title="10. Changes to These Terms">
            <TermsBody>
              We may update these Terms from time to time. We will notify you of significant changes through
              the app or by email. Continued use of the app after changes constitutes your acceptance of the
              revised Terms.
            </TermsBody>
          </TermsSection>

          <TermsSection title="11. Governing Law">
            <TermsBody>
              These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive
              jurisdiction of the courts in India.
            </TermsBody>
          </TermsSection>

          <TermsSection title="12. Contact Us">
            <TermsBody>If you have any questions about these Terms, please contact us at:</TermsBody>
            <p className="mt-2 text-sm leading-relaxed text-muted sm:text-base">
              RWE Labs<br />
              Email: <a href="mailto:rwelabs@gmail.com" className="text-accent underline/30 hover:underline">rwelabs@gmail.com</a>
            </p>
          </TermsSection>
        </div>
      </section>

      <Footer />
    </main>
  );
}

function TermsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-cream/10 py-8 sm:py-10 md:py-12">
      <h2 className="text-xl font-semibold tracking-[-0.02em] text-cream sm:text-2xl">{title}</h2>
      <div className="mt-4 space-y-4">{children}</div>
    </section>
  );
}

function TermsBody({ children }: { children: React.ReactNode }) {
  return <p className="text-sm leading-relaxed text-muted sm:text-base">{children}</p>;
}

function TermsSubheading({ children }: { children: React.ReactNode }) {
  return <h3 className="pt-1 text-sm font-semibold text-cream sm:text-base">{children}</h3>;
}

function TermsList({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2 text-sm text-muted sm:text-base">
      {items.map((item) => (
        <li key={item} className="flex items-start gap-2.5">
          <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  );
}
